version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: tradeflow-rabbitmq
    ports:
      - "5674:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: tradeflow-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tradeflow
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  timescaledb_data:
